export enum queryKeys {
    // admin
    LOGIN = "LOGIN",
    GET_DASHBOARD = "GET_DASHBOARD",
    GET_ADMIN_INFO = "GET_ADMIN_INFO",

    // events
    CREATE_EVENT = "CREATE_EVENT",
    UPDATE_EVENT = "UPDATE_EVENT",
    DELETE_EVENT = "DELETE_EVENT",
    GET_EVENTS = "GET_EVENTS",
    GET_SINGLE_EVENT = "GET_SINGLE_EVENT",
    GET_ENDING_SOON_EVENTS = "GET_ENDING_SOON_EVENTS",

    // channels
    GET_CHANNELS = "GET_CHANNELS",
    CREATE_CHANNEL = "CREATE_CHANNEL",
    UPDATE_CHANNEL = "UPDATE_CHANNEL",
    DELETE_CHANNEL = "DELETE_CHANNEL",

    // candidates
    GET_CANDIDATES = "GET_CANDIDATES",
    CREATE_CANDIDATE = "CREATE_CANDIDATE",
    UPDATE_CANDIDATE = "UPDATE_CANDIDATE",
    DELETE_CANDIDATE = "DELETE_CANDIDATE",
}
